# Generated by Django 3.0.8 on 2020-07-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiscoRouterInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ipv4_address', models.CharField(blank=True, max_length=100, null=True)),
                ('ipv4_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cisco.CiscoRouter')),
            ],
        ),
    ]
