# Generated by Django 3.0.8 on 2020-07-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0002_ciscorouterinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vrf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rt', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RouterLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.CharField(blank=True, max_length=100, null=True)),
                ('vlan', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='cisco.CiscoRouter')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='cisco.CiscoRouter')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cisco.Vrf')),
            ],
        ),
    ]
