# Generated by Django 3.0.8 on 2020-07-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0003_routerlinks_vrf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouterLinks',
            new_name='RouterLink',
        ),
    ]
