# Generated by Django 3.0.8 on 2020-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0004_auto_20200715_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerlink',
            name='ipv4_mask',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='routerlink',
            name='ipv4_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
