# Generated by Django 3.0.8 on 2020-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0005_auto_20200715_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciscorouterinterface',
            name='ipv4_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
