# Generated by Django 3.0.8 on 2020-07-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0006_ciscorouterinterface_ipv4_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciscorouterinterface',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisco.CiscoRouter'),
        ),
        migrations.AlterUniqueTogether(
            name='ciscorouterinterface',
            unique_together={('name', 'router')},
        ),
    ]
