# Generated by Django 3.0.8 on 2020-07-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0008_auto_20200715_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerlink',
            name='ipv4_address',
        ),
        migrations.RemoveField(
            model_name='routerlink',
            name='ipv4_mask',
        ),
        migrations.RemoveField(
            model_name='routerlink',
            name='ipv4_network',
        ),
        migrations.RemoveField(
            model_name='routerlink',
            name='vlan',
        ),
        migrations.RemoveField(
            model_name='routerlink',
            name='vrf',
        ),
        migrations.AddField(
            model_name='ciscorouterinterface',
            name='vlan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ciscorouterinterface',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cisco.Vrf'),
        ),
    ]
