# Generated by Django 3.0.8 on 2020-07-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0009_auto_20200716_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerlink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='cisco.CiscoRouterInterface'),
        ),
        migrations.AlterField(
            model_name='routerlink',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='cisco.CiscoRouterInterface'),
        ),
    ]
