# Generated by Django 3.0.8 on 2020-07-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0010_auto_20200716_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrf',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vrfs', to='cisco.CiscoRouter'),
        ),
        migrations.AlterField(
            model_name='ciscorouterinterface',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='cisco.CiscoRouter'),
        ),
    ]
